=== william1130/demo/src/resource/iso8583.dtd
<!ELEMENT ISO8583-config ( header*, parse+, table*, chip*, token*, b24-tlv* ) >
<!ATTLIST ISO8583-config encoding NMTOKEN #IMPLIED >
<!ATTLIST ISO8583-config desc CDATA #IMPLIED >
<!ATTLIST ISO8583-config type NMTOKEN #IMPLIED >
<!ATTLIST ISO8583-config dataOnly NMTOKEN #IMPLIED >

<!ELEMENT header ( #PCDATA ) >
<!ATTLIST header length NMTOKEN #REQUIRED >
<!ATTLIST header ref CDATA #REQUIRED >

<!ELEMENT parse ( field+ ) >
<!ATTLIST parse id NMTOKEN #REQUIRED >
<!ATTLIST parse desc CDATA #IMPLIED >
<!ATTLIST parse mti NMTOKEN #IMPLIED >

<!ELEMENT field ( parse* , field*, redefine* ) >
<!ATTLIST field num NMTOKEN #REQUIRED >
<!ATTLIST field length NMTOKEN #IMPLIED >
<!ATTLIST field type ( ALPHA | NUMERIC | AMOUNT | DATE10 | DATE4 | DATE_EXP | TIME | LLVAR | LLLVAR | BINARY | CHINESE | LLBIN | LLLBIN | LLZ | LLLTABLES | LLLCHIP | LLLTOKENS | LLLLTOKENS | POSKITZTAG | SMARTPAYCHIP | SMARTPAYTAG | REDEF | LLLBITMAPVAR | ZIP | B24TLV | EBCDIC | VAR | LLBINHEX | LLLBINHEX ) #REQUIRED >
<!ATTLIST field alt NMTOKEN #IMPLIED >
<!ATTLIST field desc CDATA #IMPLIED >
<!ATTLIST field ref CDATA #IMPLIED >

<!ELEMENT redefine ( define* ) >
<!ATTLIST redefine default-ref NMTOKEN #IMPLIED >

<!ELEMENT define ( #PCDATA ) >
<!ATTLIST define ref CDATA #REQUIRED >
<!ATTLIST define selector-expression CDATA #REQUIRED >

<!ELEMENT table ( table-parse+ ) >
<!ELEMENT table-parse ( table-field+ ) >
<!ATTLIST table-parse id NMTOKEN #REQUIRED >
<!ATTLIST table-parse desc CDATA #IMPLIED >
<!ATTLIST table-parse mti NMTOKEN #IMPLIED >
<!ATTLIST table-parse length-type NMTOKEN #IMPLIED >

<!ELEMENT table-field ( #PCDATA ) >
<!ATTLIST table-field num NMTOKEN #REQUIRED >
<!ATTLIST table-field length NMTOKEN #IMPLIED >
<!ATTLIST table-field type ( ALPHA | NUMERIC | AMOUNT | DATE10 | DATE4 | DATE_EXP | TIME | LLVAR | LLLVAR | BINARY | CHINESE | LLBIN | LLLBIN | LLZ | CHECKSUM | LBINARY | LVAR | ZIP | VAR | B24TLV ) #REQUIRED >
<!ATTLIST table-field alt NMTOKEN #IMPLIED >
<!ATTLIST table-field desc CDATA #IMPLIED >
<!ATTLIST table-field ref CDATA #IMPLIED >

<!ELEMENT chip ( chip-field+ ) >
<!ATTLIST chip dublebytestag CDATA #REQUIRED >
<!ATTLIST chip triplebytestag CDATA #IMPLIED >

<!ELEMENT chip-field ( #PCDATA ) >
<!ATTLIST chip-field tag NMTOKEN #REQUIRED >
<!ATTLIST chip-field length NMTOKEN #REQUIRED >
<!ATTLIST chip-field desc CDATA #IMPLIED >

<!ELEMENT token ( token-parse+ ) >
<!ELEMENT token-parse ( token-field+ ) >
<!ATTLIST token-parse id CDATA #REQUIRED >
<!ATTLIST token-parse desc CDATA #IMPLIED >
<!ATTLIST token-parse mti NMTOKEN #IMPLIED >
<!ATTLIST token-parse fill-in CDATA #IMPLIED preferred (none | odd | even) "none" >
<!ATTLIST token-parse padding-str CDATA #IMPLIED >

<!ELEMENT token-field ( token-redefine* ) >
<!ATTLIST token-field num NMTOKEN #REQUIRED >
<!ATTLIST token-field length NMTOKEN #IMPLIED >
<!ATTLIST token-field type ( ALPHA | NUMERIC | AMOUNT | DATE10 | DATE4 | DATE_EXP | TIME | LLVAR | LLLVAR | BINARY | LLBIN | LLLBIN | LLZ | LVAR | REDEF | B24TLV | VAR) #REQUIRED >
<!ATTLIST token-field alt NMTOKEN #IMPLIED >
<!ATTLIST token-field desc CDATA #IMPLIED >
<!ATTLIST token-field ref CDATA #IMPLIED >

<!ELEMENT token-redefine ( token-define* ) >
<!ATTLIST token-redefine default-ref NMTOKEN #IMPLIED >

<!ELEMENT token-define ( #PCDATA ) >
<!ATTLIST token-define ref CDATA #REQUIRED >
<!ATTLIST token-define selector-expression CDATA #REQUIRED >


<!ELEMENT b24-tlv ( b24-tlv-field+ ) >

<!ELEMENT b24-tlv-field ( #PCDATA ) >
<!ATTLIST b24-tlv-field tag NMTOKEN #REQUIRED >
<!ATTLIST b24-tlv-field type ( ALPHA | NUMERIC | AMOUNT | DATE10 | DATE4 | DATE_EXP | TIME | LLVAR | LLLVAR | BINARY | LLBIN | LLLBIN | LLZ | LVAR | REDEF | B24TLV | VAR) #REQUIRED >
<!ATTLIST b24-tlv-field desc CDATA #IMPLIED >

=== william1130/demo/src/resource/ISO8583_EDC_AE.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE ISO8583-config SYSTEM "iso8583.dtd">
<ISO8583-config encoding="BIG5" desc="ISO8583 AE設定檔" type="BINARY">
	<header length="5" ref="default">TPDU</header>
	<parse id="default" desc="通用規格">
		<field num="2" type="LLZ" desc="PAN" alt="posfix:f" />
		<field num="3" type="NUMERIC" length="6" desc="Processing Code" />
		<field num="4" type="AMOUNT" desc="Amount, Transaction" />
		<field num="11" type="NUMERIC" length="6" desc="System Trace Audit Number" />
		<field num="12" type="TIME" desc="Time, Local Transaction" />
		<field num="13" type="DATE4" desc="Date, Local Transaction" />
		<field num="14" type="NUMERIC" length="4" desc="Date, Expired" />
		<field num="15" type="DATE4" desc="Date, Local Transaction2" />
		<field num="22" type="NUMERIC" length="4" desc="POS Entry Mode" />
		<field num="24" type="NUMERIC" length="4" desc="Network International Identifier" />
		<field num="25" type="NUMERIC" length="2" desc="POS Condition Code" />
		<field num="35" type="LLZ" desc="Track 2 Data" alt="posfix:f" />
		<field num="37" type="ALPHA" length="12" desc="Retrieval Reference Number" />
		<field num="38" type="ALPHA" length="6" desc="Authorization Identification Response" />
		<field num="39" type="ALPHA" length="2" desc="Response Code" />
		<field num="41" type="ALPHA" length="8" desc="Card Acceptor Terminal Identification" />
		<field num="42" type="ALPHA" length="15" desc="Card Acceptor Identification Code" />
		<field num="44" type="LLVAR" desc="Additional Data – Resp data" />
		<field num="45" type="LLVAR" desc="Track 1" />
		<field num="48" type="LLLVAR" desc="Additional Data – Private Use" />
		<field num="52" type="BINARY" length="8" desc="Pinblock Data" />
		<field num="54" type="LLLVAR" desc="Additional Amount" />
		<field num="55" type="LLLVAR" desc="EMV Chip Data" />
		<field num="60" type="LLLVAR" desc="Reserved – Private Data" ref="f60" /> 
		<field num="61" type="LLLVAR" desc="Reserved – Private Data" />
		<field num="62" type="LLLVAR" desc="Reserved – Private Data" />
		<field num="63" type="LLLVAR" desc="Reserved – Private Data"  />
	</parse>
	<parse id="f60" desc="Batch Totals for Close Batch" mti="0320">
		<field num="1" type="ALPHA" length="4" desc="Message type" />
		<field num="2" type="ALPHA" length="6" desc="STAN" />
		<field num="3" type="ALPHA" length="12" desc="Reserved for future use" />
	</parse>
	<parse id="f60" desc="Batch Totals for Close Batch" mti="0500">
		<field num="1" type="ALPHA" length="6" desc="Message type" />
	</parse>
</ISO8583-config>

=== william1130/demo/src/resource/ISO8583_EDC_GEDC.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE ISO8583-config SYSTEM "iso8583.dtd">
<ISO8583-config encoding="BIG5" desc="ISO8583 AE GEDC設定檔" type="BINARY">
	<header length="5" ref="default">TPDU</header>
	<parse id="default" desc="通用規格">
		<field num="2" type="LLZ" desc="PAN" alt="posfix:f" />
		<field num="3" type="NUMERIC" length="6" desc="Processing Code" />
		<field num="4" type="AMOUNT" desc="Amount, Transaction" />
		<field num="7" type="NUMERIC" desc="Date And Time, Transmission" />
		<field num="11" type="NUMERIC" length="6" desc="System Trace Audit Number" />
		<field num="12" type="TIME" desc="Time, Local Transaction" />
		<field num="13" type="DATE4" desc="Date, Local Transaction" />
		<field num="14" type="NUMERIC" length="4" desc="Date, Expired" />
		<field num="15" type="DATE4" desc="Date, Local Transaction2" />
		<field num="22" type="NUMERIC" length="4" desc="POS Entry Mode" />
		<field num="24" type="NUMERIC" length="4" desc="Network International Identifier" />
		<field num="25" type="NUMERIC" length="2" desc="POS Condition Code" />
		<field num="32" type="LLBIN" desc="Acquiring Institution Identification Code" />
		<field num="35" type="LLZ" desc="Track 2 Data" alt="posfix:f" />
		<field num="37" type="ALPHA" length="12" desc="Retrieval Reference Number" />
		<field num="38" type="ALPHA" length="6" desc="Authorization Identification Response" />
		<field num="39" type="ALPHA" length="2" desc="Response Code" />
		<field num="41" type="ALPHA" length="8" desc="Card Acceptor Terminal Identification" />
		<field num="42" type="ALPHA" length="15" desc="Card Acceptor Identification Code" />
		<field num="43" type="ALPHA" length="40" desc="Card Acceptor Name/Location" />
		<field num="44" type="LLVAR" desc="Additional Data – Resp data" />
		<field num="45" type="LLVAR" desc="Track 1" />
		<field num="47" type="LLLVAR" desc="Additional Data - National" />
		<field num="48" type="LLLVAR" desc="Additional Data – Private Use" />
		<field num="49" type="LLLVAR" desc="CurrencyCode, Transaction" />
		<field num="52" type="BINARY" length="8" desc="Pinblock Data" />
		<field num="54" type="LLLVAR" desc="Additional Amount" />
		<field num="55" type="LLLBIN" desc="ISO USE DATA" ref="f55" />
		<field num="59" type="LLLVAR" desc="National Use Data" />
		<field num="60" type="LLLVAR" desc="Reserved – Private Data" ref="f60" /> 
		<field num="61" type="LLLVAR" desc="Reserved – Private Data" />
		<field num="62" type="LLLVAR" desc="Reserved – Private Data" />
		<field num="63" type="LLLVAR" desc="Reserved – Private Data"  />
		<field num="64" type="BINARY" length="8" desc="Reserved – Private Data" />
	</parse>
	
	<parse id="f55" desc="ISO USE DATA">
        <field num="1" type="REDEF">
            <redefine default-ref="f55_reuqest">
            	<define selector-expression="buf.length == 4" ref="f55_4dbc" />
            	<define selector-expression="vo.getMti().toString().endsWith('10') || vo.getMti().toString().endsWith('30')" ref="f55_response" />
            </redefine>
        </field>
    </parse>
	
	<parse id="f55_4dbc">
		<field num="1" type="ALPHA" length="4" desc="Card Identifier (CID)" />
	</parse>
	
	<parse id="f55_reuqest">
		<field num="1" type="EBCDIC" length="4" desc="Version Header" />
		<field num="2" type="BINARY" length="2" desc="Version Number" />
		<field num="3" type="BINARY" length="8" desc="9F26" />
		<field num="4" type="LLBINHEX" desc="9F10" />
		<field num="5" type="BINARY" length="4" desc="9F37" />
		<field num="6" type="BINARY" length="2" desc="9F36" />
		<field num="7" type="BINARY" length="5" desc="95" />
		<field num="8" type="BINARY" length="3" desc="9A" />
		<field num="9" type="BINARY" length="1" desc="9C" />
		<field num="10" type="BINARY" length="6" desc="9F02" />
		<field num="11" type="BINARY" length="2" desc="5F2A" />
		<field num="12" type="BINARY" length="2" desc="9F1A" />
		<field num="13" type="BINARY" length="2" desc="82" />
		<field num="14" type="BINARY" length="6" desc="9F03" />
		<field num="15" type="BINARY" length="1" desc="5F34" />
		<field num="16" type="BINARY" length="1" desc="9F27" />
		<field num="17" type="LLBINHEX" desc="9F06" />
		<field num="18" type="BINARY" length="2" desc="9F09" />
		<field num="19" type="BINARY" length="3" desc="9F34" />
		<field num="20" type="BINARY" length="5" desc="9F0E" />
		<field num="21" type="BINARY" length="5" desc="9F0F" />
		<field num="22" type="BINARY" length="5" desc="9F0D" />
		<field num="23" type="LLBINHEX" desc="Reserved for future use" />
	</parse>
	
	<parse id="f55_response">
		<field num="1" type="EBCDIC" length="4" desc="Version Header" />
		<field num="2" type="BINARY" length="2" desc="Version Number" />
		<field num="3" type="LLBINHEX" desc="91" />
		<field num="4" type="LLBINHEX" desc="Issuer Script Data" />
		<field num="5" type="LLBINHEX" desc="Reserved for future use" />
	</parse>
	
	<parse id="f60" desc="Batch Totals for Close Batch" mti="0320">
		<field num="1" type="ALPHA" length="4" desc="Message type" />
		<field num="2" type="ALPHA" length="6" desc="STAN" />
		<field num="3" type="ALPHA" length="12" desc="Reserved for future use" />
	</parse>
	<parse id="f60" desc="Batch Totals for Close Batch" mti="0500">
		<field num="1" type="ALPHA" length="6" desc="Message type" />
	</parse>
	
</ISO8583-config>

=== william1130/demo/src/resource/ISO8583_TMS.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE ISO8583-config SYSTEM "iso8583.dtd">
<ISO8583-config encoding="BIG5">
	<header length="5" ref="default">TPDU</header>
	<parse id="default" desc="通用規格">
		<field num="3" type="NUMERIC" length="6" desc="Processing Code" />
		<field num="11" type="NUMERIC" length="6" desc="System Trace Audit Number" />
        <field num="12" type="TIME" desc="Time, Local Transaction" />
        <field num="13" type="DATE4" desc="Date, Local Transaction" />
		<field num="24" type="NUMERIC" length="3" desc="Network International Identifier" />
		<field num="39" type="ALPHA" length="2" desc="Response Code" />
		<field num="41" type="ALPHA" length="8" desc="Card Acceptor Terminal Identification" />
		<field num="42" type="ALPHA" length="15" desc="Card Acceptor Identification Code" />
		<field num="58" type="LLLVAR" desc="Reserved – Private Data" ref="f58" />
		<field num="61" type="LLLVAR" desc="Reserved – Private Data" />
	</parse>
	<parse id="f58" desc="Batch Totals for Close Batch">
		<field num="1" type="ALPHA" length="8" desc="Host Date (TMS)" />
		<field num="2" type="ALPHA" length="6" desc="Host Time (TMS)" />
		<field num="3" type="ALPHA" length="1" desc="Download Flag" />
		<field num="4" type="ALPHA" length="1" desc="Download Scope" />
		<field num="5" type="ALPHA" length="15" desc="Download TEL" />
		<field num="6" type="ALPHA" length="8" desc="Schedule Date" />
		<field num="7" type="ALPHA" length="6" desc="Schedule Time" />
	</parse>
</ISO8583-config>

=== william1130/demo/src/resource/ISO8583_IPASS.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE ISO8583-config SYSTEM "iso8583.dtd">
<ISO8583-config encoding="BIG5" desc="ipass 設定檔" type="STRING">
	<header length="8" ref="default">FFFF9999</header>
	<parse id="default" desc="IPass">
		<field num="7" type="NUMERIC" length="10" desc="Transmission Date and Time" />
		<field num="11" type="NUMERIC" length="6" desc="System Trace Audit Number" />
		<field num="13" type="NUMERIC" length="4" desc="Transmission Year" />
		<field num="39" type="ALPHA" length="2" desc="Response Code" />
		<field num="70" type="NUMERIC" length="3" desc="Network Management Information Code" />
	</parse>
</ISO8583-config>

=== william1130/demo/src/resource/ISO8583_SPSW.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE ISO8583-config SYSTEM "iso8583.dtd">
<ISO8583-config encoding="BIG5" desc="SmartPay設定檔" type="BINARY">
	<header length="12" ref="default">SPI000000000</header>
	<parse id="default" desc="通用規格">
		<field num="3" type="NUMERIC" length="6" desc="Processing Code" />
		<field num="4" type="AMOUNT" desc="Amount, Transaction" />
		<field num="7" type="NUMERIC" length="10" desc="服務系統日期時間" />
		<field num="11" type="NUMERIC" length="6" desc="System Trace Audit Number" />
		<field num="12" type="TIME" desc="Time, Local Transaction" />
		<field num="13" type="DATE4" desc="Date, Local Transaction" />
		<field num="24" type="NUMERIC" length="3" desc="Network International Identifier" />
		<field num="25" type="NUMERIC" length="2" desc="POS Condition Code" />
		<field num="35" type="LLBIN" desc="卡片基本資料" ref="f35" />
		<field num="37" type="ALPHA" length="12" desc="Retrieval Reference Number" />
		<field num="39" type="ALPHA" length="2" desc="Response Code" />
		<field num="41" type="ALPHA" length="8" desc="Card Acceptor Terminal Identification" />
		<field num="42" type="ALPHA" length="15" desc="Card Acceptor Identification Code" />
		<field num="45" type="LLVAR" desc="促銷欄位" />
		<field num="55" type="SMARTPAYCHIP" desc="晶片卡交易資料" />
		<field num="58" type="SMARTPAYTAG" desc="Additional Data" />
		<field num="60" type="ALPHA" length="8" desc="端末設備查核碼" />
		<field num="61" type="LLLVAR" desc="收單行代號+收單處理單位代號" ref="f61" />
		<field num="62" type="LLLVAR" desc="訂單號碼" />
		<field num="63" type="LLLBIN" desc="原始交易資料" ref="f63" />
		<field num="64" type="BINARY" length="4" desc="MAC" />
	</parse>
	<parse id="f35" desc="卡片基本資料">
		<field num="1" type="ALPHA" length="8" desc="發卡單位代號(左靠右補0)" />
		<field num="2" type="ALPHA" length="16" desc="帳號" />
		<field num="3" type="BINARY" length="30" desc="備註欄" />
	</parse>
	<parse id="f61" desc="收單行代號+收單處理單位代號">
		<field num="1" type="ALPHA" length="3" desc="收單行代號" />
		<field num="2" type="ALPHA" length="4" desc="收單處理單位代號" />
	</parse>
	<parse id="f63" desc="原始交易資料">
		<field num="1" type="REDEF" desc="原始交易資料">
			<redefine default-ref="f63_reversal">
				<define selector-expression="vo.mti.mtic == T(com.hp.nccc.iso8583.common.ISO8583Context$MTIClass).Financial_Transaction and vo.mti.mtim == T(com.hp.nccc.iso8583.common.ISO8583Context$MTIMode).Issuer_Reconciliation_Request" ref="f63_confirm" />
				<define selector-expression="vo.getField(3).toString().equals('002120')" ref="f63_search" />
			</redefine>
		</field>
	</parse>
	<parse id="f63_reversal" desc="沖正交易原資料">
		<field num="1" type="ALPHA" length="8" desc="(原)端末設備查核碼" />
		<field num="2" type="ALPHA" length="8" desc="(原)端末設備代號" />
		<field num="3" type="NUMERIC" length="14" desc="(原)交易日期、時間" />
		<field num="4" type="ALPHA" length="12" desc="(原)RRN" />
	</parse>
	<parse id="f63_confirm" desc="confirm 原資料">
		<field num="1" type="NUMERIC" length="14" desc="(原)交易日期、時間" />
	</parse>
	<parse id="f63_search" desc="查詢 原資料">
		<field num="1" type="ALPHA" length="8" desc="(原)發卡單位代號" />
		<field num="2" type="ALPHA" length="16" desc="(原)帳號" />
	</parse>
	<chip dublebytestag="">
		<chip-field tag="10" length="1" desc="Transmission Date and Time (GMT)" />
		<chip-field tag="11" length="1" desc="Reason Code Description" />
	</chip>
</ISO8583-config>

=== william1130/demo/src/resource/ISO8583_TKS.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE ISO8583-config SYSTEM "iso8583.dtd">
<ISO8583-config encoding="BIG5" desc="電子票證設定檔" type="BINARY">
	<header length="12" ref="default">SPI000000000</header>
	<parse id="default" desc="通用規格">
		<field num="3" type="NUMERIC" length="6" desc="Processing Code" />
		<field num="4" type="AMOUNT" desc="Amount, Transaction" />
		<field num="11" type="NUMERIC" length="6" desc="System Trace Audit Number" />
		<field num="12" type="TIME" desc="Time, Local Transaction" />
		<field num="13" type="DATE4" desc="Date, Local Transaction" />
		<field num="32" type="NUMERIC" length="4" desc="Acquiring Institution Identification Code" />
		<field num="35" type="LLVAR" desc="卡片基本資料" />
		<field num="38" type="ALPHA" length="6" desc="Authorization Identification Response" />
		<field num="39" type="ALPHA" length="2" desc="Response Code" />
		<field num="41" type="ALPHA" length="8" desc="Card Acceptor Terminal Identification" />
		<field num="42" type="ALPHA" length="15" desc="Card Acceptor Identification Code" />
		<field num="56" type="LLLTABLES" desc="Reserved – Private Data" />
	</parse>
	<table>
		<table-parse id="EZ01" desc="悠遊卡交易資料">
			<table-field num="1" type="LBINARY" desc="EZ Card Transaction Data" />
		</table-parse>
		<table-parse id="IP00" desc="一卡通交易主機資料">
            <table-field num="1" type="ALPHA" length="2" desc="本交易對應一卡通之主機" />
        </table-parse>
        <table-parse id="IP01" desc="一卡通交易資料">
            <table-field num="1" type="LBINARY" desc="iPass Card Transaction Data" />
        </table-parse>
        <table-parse id="IC01" desc="愛金卡交易資料">
            <table-field num="1" type="LBINARY" desc="愛金卡交易資料" />
        </table-parse>
        <table-parse id="HC01" desc="遠鑫卡交易資料">
            <table-field num="1" type="LBINARY" desc="遠鑫卡交易資料" />
        </table-parse>
        <table-parse id="SW01" desc="電子票證主機回應碼">
            <table-field num="1" type="LBINARY" desc="電子票證主機回應碼" />
        </table-parse>
        <!-- M2022086 -->
        <table-parse id="LP00" desc="LINE Pay Header 資料">
            <table-field num="1" type="LBINARY" desc="LINE Pay Header 資料" />
        </table-parse>
        <table-parse id="LP01" desc="LINE Pay交易資料">
            <table-field num="1" type="LBINARY" desc="LINE Pay交易資料" />
        </table-parse>
        <table-parse id="EP00" desc="悠遊付 Header 資料">
            <table-field num="1" type="LBINARY" desc="悠遊付 Header Data" />
        </table-parse>
        <table-parse id="EP01" desc="悠遊付交易資料">
            <table-field num="1" type="LBINARY" desc="悠遊付 Transaction Data" />
        </table-parse>
        <table-parse id="PX00" desc="全支付(PX Pay)Header 資料">
            <table-field num="1" type="LBINARY" desc="全支付(PX Pay)Header 資料" />
        </table-parse>
        <table-parse id="PX01" desc="全支付(PX Pay)交易資料">
            <table-field num="1" type="LBINARY" desc="全支付(PX Pay)交易資料" />
        </table-parse>
        <table-parse id="PP01" desc="全盈+支付(PlusPay)交易資料">
            <table-field num="1" type="LBINARY" desc="全盈+支付(PlusPay)交易資料" />
        </table-parse>
        <table-parse id="PI01" desc="Pi錢包交易資料">
            <table-field num="1" type="LBINARY" desc="Pi錢包交易資料" />
        </table-parse>
        <table-parse id="CP00" desc="iCashPay Header資料">
            <table-field num="1" type="LBINARY" desc="iCashPay Header資料" />
        </table-parse>
        <table-parse id="CP01" desc="iCashPay交易資料">
            <table-field num="1" type="LBINARY" desc="iCashPay交易資料" />
        </table-parse>
        <!-- M2022086 -->
	</table>
</ISO8583-config>
